#!/bin/bash

GENERATIONS=20
POPULATION=500
BENCHMARK_TEST_COUNT=5

for COUNT in 2 3
do
    MODEL_SUMMARY="resources/model_summaries/example_summaries/MNIST/MNIST_full_quanitization_multi_$COUNT.json"
    make profile USBMON=0 COUNT=$BENCHMARK_TEST_COUNT MODEL_SUMMARY=$MODEL_SUMMARY OUTPUT_NAME="results_$COUNT.csv" POPULATION_SIZE=$POPULATION GENERATIONS=$GENERATIONS
done
